### ISSUE TITLE
包问题

### ISSUE THREAD

**Issue by C-520-Q** [mcpaulgeorge/WalMaFa#4]
你好，作者
请问你这个包的版本是啥呀
![微信截图_20241108193018](https://github.com/user-attachments/assets/c221927a-3e19-4a46-a5b3-f558e71120de)
感谢作者

**Comment by mcpaulgeorge** [comment]
![image](https://github.com/user-attachments/assets/be2a50e4-2be0-4047-8e95-ce9e89b9f7a1)

**Comment by C-520-Q** [comment]
作者，还有visualizer包的版本，谢谢

**Comment by mcpaulgeorge** [comment]
![image](https://github.com/user-attachments/assets/282ded7b-0e08-4fa3-b0a4-62d7bf4ef7c6)
visualizer是写论文的时候可视化特征图的，预测是不需要调用的
